services:
    cmdbench:
        container_name: cmdbench
        build:
            context: ../../
            dockerfile: ./docker/services/cmdbench/Dockerfile
        working_dir: /cmdbench
        restart: always
        depends_on:
            - postgres
        environment:
            PGHOST: postgres
            PGUSER: $PGUSER
            PGDATABASE: $PGDATABASE
        command: bash -c "bash ./scripts/wait-for-postgres.sh && pytest"

    postgres:
        image: postgres:16.3
        restart: always
        volumes:
            - ../services/postgres/sql:/docker-entrypoint-initdb.d
        ports:
            - 6543:5432
        environment:
            POSTGRES_USER: $PGUSER
            POSTGRES_DB: $PGDATABASE
            POSTGRES_HOST_AUTH_METHOD: trust