services:
    cmdbench:
        container_name: cmdbench
        build:
            context: ../../
            dockerfile: ./docker/services/cmdbench/Dockerfile
        working_dir: /cmdbench
        depends_on:
            - postgres
        environment:
            PGHOST: postgres
            PGUSER: $PGUSER
            PGDATABASE_NBA: $PGDATABASE_NBA
        command: bash -c "bash ./scripts/wait-for-postgres.sh pytest"

    postgres:
        image: postgres:16.3
        volumes:
            - ../services/postgres/sh:/docker-entrypoint-initdb.d
            - ../services/postgres/sql:/init
        ports:
            - 6543:5432 # to allow connection to Postgres outside of the container
        environment:
            POSTGRES_USER: $PGUSER
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: $PGUSER
            PGDATABASE_NBA: $PGDATABASE_NBA