services:
  postgres:
    container_name: postgres
    image: postgres:16.3
    volumes:
      - ../services/postgres/sh:/docker-entrypoint-initdb.d
      - ../services/postgres/sql:/init
    ports:
      - $PGPORT:5432 # to allow connection to Postgres outside of the container
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: $PGUSER
      PGDATABASE_NBA: $PGDATABASE_NBA

  neo4j:
    container_name: neo4j
    image: megagonlabs/cmdbench-neo4j:latest
    build:
      context: ../../
      dockerfile: ./docker/services/neo4j/Dockerfile
    ports:
      - $NEO4J_BOLT_PORT:7687
      - $NEO4J_HTTP_PORT:7474
    environment:
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD

  mongo:
    container_name: mongo
    image: mongo:5.0.27
    ports:
      - $MONGO_PORT:27017
    command: [ "mongod", "--noauth" ]
    volumes:
      - ../services/mongo/sh:/docker-entrypoint-initdb.d
      - ../services/mongo/data:/init
